on: [push, pull_request]

name: Continuous integration

jobs:
  test:
    name: perform ${{ matrix.command }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: [check, test, fmt, clippy]
        include:
          - command: check
            args:
          - command: test
            args:
          - command: fmt
            args: --all -- --check
          - command: clippy
            args: -- -D warnings
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: ${{ matrix.command }}
          args: ${{ matrix.args }}
